# Generated by Django 4.2.15 on 2024-09-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('building', 'Building'), ('furniture', 'Furniture'), ('equipment', 'Equipment'), ('vehicle', 'Vehicle')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('asset_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('broken', 'Broken')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tag_number', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
    ]
